# Generated by Django 4.2.1 on 2023-08-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='tariner_name',
            new_name='trainer_name',
        ),
    ]
